---
title: "Aula2"
format: pdf
---

```{r}
library(DBI)
library(RSQLite)
con <- dbConnect(SQLite(), "me315.sqlite")
```

Os exercícios a seguir fazem referência à tabela PRESERVE.

1. Selecione as colunas STATE, PNO e PNAME e exiba todas as linhas, ordenadas pelos valores de STATE em ordem crescente.
```{sql connection=con}
SELECT STATE, PNO, PNAME 
FROM PRESERVE 
ORDER BY STATE
```

2. Selecione as colunas STATE, PNO e PNAME e exiba todas as linhas, ordenadas pelos valores de STATE em ordem decrescente.
```{sql connection=con}
SELECT STATE, PNO, PNAME 
FROM PRESERVE 
ORDER BY STATE DESC
```

3. Selecione as colunas STATE, PNO e PNAME e exiba todas as linhas, ordenadas pelos valores de STATE e PNO, ambos em forma decrescente.
```{sql connection=con}
SELECT STATE, PNO, PNAME 
FROM PRESERVE 
ORDER BY STATE DESC, PNO DESC
```

4. Selecione as colunas STATE, PNO e PNAME e exiba todas as linhas, ordenadas em ordem decrescente pelos valores de PNO, nas quais STATE é "AZ".
```{sql connection=con}
SELECT STATE, PNO, PNAME 
FROM PRESERVE 
WHERE STATE == "AZ" 
ORDER BY PNO DESC
```

5. Exiba o número da reserva (PNO), a área em acres (ACRES) e o nome de cada reserva natural (PNAME) localizada no estado de Arizona. Ordene o resultado pela terceira coluna.
```{sql connection=con}
SELECT PNO, ACRES, PNAME 
FROM PRESERVE 
WHERE STATE == "AZ" 
ORDER BY 3
```

6. Exiba a tabela PRESERVE inteira, ordenada pela quarta coluna em ordem descendente e a segunda coluna em ordem crescente.
```{sql connection=con}
SELECT * 
FROM PRESERVE 
ORDER BY 4 DESC, 2
```

7. Exiba os valores de PNO e PNAME de todas as reservas. Apresente o resultado ordenado por ACRES, em ordem decrescente.
```{sql connection=con}
SELECT PNO, PNAME 
FROM PRESERVE 
ORDER BY ACRES DESC
```

8. Exiba os valores de STATE, FEE e PNAME de todas as linhas da tabela PRESERVE, em que:
    (i)   STATE é a 1ª coluna de ordenação (ordem crescente);
    (ii)  FEE é a 2ª coluna de ordenação (ordem decrescente);
    (iii) PNAME é a 3ª coluna de ordenação (ordem decrescente).
```{sql connection=con}
SELECT STATE, FEE, PNAME 
FROM PRESERVE 
ORDER BY STATE, FEE DESC, PNAME DESC
```

9. Exiba os valores de PNO e ACRES das três primeiras linhas (ordenadas pelos valores do PNO).
```{sql connection=con}
SELECT PNO, ACRES 
FROM PRESERVE 
ORDER BY PNO 
LIMIT 3
```

Ordem na consulta:
SELECT ...
FROM ...
WHERE ...
ORDER BY ...
LIMIT ...;
